name:                myawesomeserver
version:             0.0.1
synopsis:            It's a server!
description:         Example for usage of composite.
homepage:            https://github.com/ConferHealth/composite#readme
license:             BSD3
author:              Confer Health, Inc.
maintainer:          oss@confer.health
copyright:           2017 Confer Health, Inc.
category:            Records

default-extensions:
  - Arrows
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 1.1.2.0 && < 1.3
  - bytestring >= 0.10.8.1 && < 0.11
  - classy-prelude >= 1.2.0.1 && < 1.5
  - composite-aeson >= 0.5.3.0 && < 0.6
  - composite-base >= 0.5.3.0 && < 0.6
  - composite-ekg >= 0.5.3.0 && < 0.6
  - composite-opaleye >= 0.5.3.0 && < 0.6
  - composite-swagger >= 0.5.3.0 && < 0.6
  - configurator >= 0.3.0.0 && < 0.4
  - ekg >= 0.1.1.3 && < 0.5
  - ekg-core >= 0.1.1.3 && < 0.5
  - exceptions >= 0.8.3 && < 0.9
  - fast-logger >= 2.4.10 && < 2.5
  - http-api-data >= 0.3.7.1 && < 0.4
  - insert-ordered-containers >= 0.2.1.0 && < 0.3
  - lens >= 4.15.4 && < 4.17
  - monad-control >= 1.0.2.2 && < 1.1
  - monad-logger >= 0.3.25.1 && < 0.4
  - mtl >= 2.2.1 && < 2.3
  - opaleye >= 0.5.4.0 && < 0.7
  - postgresql-simple >= 0.5.3.0 && < 0.6
  - product-profunctors >= 0.8.0.3 && < 0.10
  - profunctors >= 5.2.1 && < 5.3
  - resource-pool >= 0.2.3.2 && < 0.3
  - servant >= 0.11 && < 0.14
  - servant-server >= 0.11.0.1 && < 0.14
  - servant-swagger >= 1.1.4 && < 1.2
  - servant-swagger-ui >= 0.2.4.3.4.0 && < 0.3
  - swagger2 >= 2.1.6 && < 2.3
  - text >= 1.2.2.2 && < 1.3
  - vinyl >= 0.5.3 && < 0.8.2
  - warp >= 3.2.13 && < 3.3

ghc-options:
  - -Wall

executables:
  myawesomeserver-exe:
    source-dirs:      app
    main:             Main.hs
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N
    dependencies:     myawesomeserver

library:
  source-dirs:        src
  other-modules: Paths_myawesomeserver
