resolver: lts-11.5
packages:
  - composite-aeson
  - composite-aeson-refined
  - composite-base
  - composite-ekg
  - composite-opaleye
  - composite-swagger
  - example
flags: {}
extra-deps:
  - vinyl-0.8.1.1
extra-package-dbs: []
nix:
  packages:
    - postgresql
    - zlib
