name:                composite-opaleye
version:             0.5.3.0
synopsis:            Opaleye SQL for Frames records
description:         Integration between Frames records and Opaleye SQL, allowing records to be stored, retrieved, and queried from PostgreSQL.
homepage:            https://github.com/ConferHealth/composite#readme
license:             BSD3
author:              Confer Health, Inc.
maintainer:          oss@confer.health
copyright:           2017 Confer Health, Inc.
category:            Records

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - composite-base
  - opaleye
  - postgresql-simple
  - product-profunctors
  - profunctors
  - template-haskell
  - text

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src

tests:
  composite-opaleye-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans
    dependencies:
      - QuickCheck
      - composite-opaleye
      - hspec
